name: birthday_quest_app
description: A fun birthday quest app
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.1.1 # To show toast messages
  animated_text_kit: ^4.2.1 # For fun text animations
  flutter_spinkit: ^5.1.0 # To use pre-built animations
  shared_preferences: ^2.0.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0 # Check for the latest version on pub.dev

flutter_icons:
  android: true
  ios: true
  image_path: assets/icon_heart.png # Path to your icon file

flutter:
  uses-material-design: true
  assets:
    - assets/balloon.png
    - assets/icon_heart.png # Add your icon file to the assets
    - assets/right.png
    - assets/top_left.png
    - assets/top_right.png
    - assets/cake.png
    - assets/bottom_left.png

  fonts:
    - family: Oldenburg
      fonts:
        - asset: assets/fonts/Oldenburg-Regular.ttf
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-VariableFont_wght.ttf
